version: '3.8' # Compose version on docs.docker.com

services:
  frontend:
    build:
      context: .  # Dockerfile for the frontend
    ports:
      - "3000:3000"  
    depends_on:
      - backend

  backend:
    build:
      context: ./backend  # Directory containing the Dockerfile for the backend
    ports:
      - "5000:5000"
    # depends_on:
    #   - mongodb

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
